### ISSUE TITLE
Fix Tabulations

### ISSUE THREAD

**Issue by garu2** [garu2/Skills-CSS#4]
I think the tabulations are exaggerated, if they could be reduced a little 
```css
.box {
	width: 50px;
	height: 100px;
	background-color: green;
	box-shadow: 50px  0px  white, 100px  0px  red;
}
```
